apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ template "openDCIM.fullname" . }}
  labels:
    app: {{ template "openDCIM.name" . }}
    chart: {{ template "openDCIM.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: {{ template "openDCIM.name" . }}
      release: {{ .Release.Name }}
  strategy:
    rollingUpdate:
      maxUnavailable: 1
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: {{ template "openDCIM.name" . }}
        release: {{ .Release.Name }}
    spec:
      containers:
      - envFrom:
        - configMapRef:
          name: {{ .Release.Name }}-configmap
        - name: {{ .Chart.Name }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name: http
              containerPort: 80
              protocol: TCP
          livenessProbe:
            httpGet:
              path: /
              port: http
          readinessProbe:
            httpGet:
              path: /
              port: http
        volumeMounts:
{{- if .Values.persistence.enabled }}
        - mountPath: /var/www/html/assets
          name: storage-volume
{{- end }}
      volumes:
      - name: storage-volume
      {{- if .Values.persistence.pv.enabled }}
        persistentVolumeClaim:
          claimName: {{ .Values.persistence.existingClaim | default ( include "openDCIM.fullname" . ) }}
      {{- else }}
        emptyDir: {}
      {{- end }}
          - mountPath: /var/www/html/assets
            name: opendcim-persistent-storage

