apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ template "openDCIM.fullname" . }}
  labels:
    app: {{ template "openDCIM.name" . }}
    chart: {{ template "openDCIM.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: {{ template "openDCIM.name" . }}
      release: {{ .Release.Name }}
  strategy:
    rollingUpdate:
      maxUnavailable: 1
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: {{ template "openDCIM.name" . }}
        release: {{ .Release.Name }}
    spec:
      containers:
      - envFrom:
        - configMapRef:
          name: {{ .Release.Name }}-configmap
        - name: {{ .Chart.Name }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name: http
              containerPort: 80
              protocol: TCP
          livenessProbe:
            httpGet:
              path: /
              port: http
          readinessProbe:
            httpGet:
              path: /
              port: http
          volumeMounts:
          - mountPath: /var/www/html/assets
            name: opendcim-persistent-storage
          resources:
{{ toYaml .Values.resources | indent 12 }}
    {{- with .Values.nodeSelector }}
      nodeSelector:
{{ toYaml . | indent 8 }}
    {{- end }}
    {{- with .Values.affinity }}
      affinity:
{{ toYaml . | indent 8 }}
    {{- end }}
    {{- with .Values.tolerations }}
      tolerations:
{{ toYaml . | indent 8 }}
    {{- end }}
      volumes:
      - name: opendcim-persistent-storage {{ if and .Values.persistence.mounttype (eq .Values.persistence.mounttype "NFS") }}
        nfs: 
          path: {{ .Values.nfs.sharepath }}
          server: {{ .Values.nfs.server }}
{{ end }}
